sites = [
    ["youtube", "https://www.youtube.com"],
    ["wikipedia", "https://www.wikipedia.org"],
    ["github", "https://github.com"],
    ["stackoverflow", "https://stackoverflow.com"],
    ["amazon", "https://www.amazon.com"],
    ["reddit", "https://www.reddit.com"],
    ["twitter", "https://twitter.com"],
    ["linkedin", "https://www.linkedin.com"],
    ["ebay", "https://www.ebay.com"],
    ["instagram", "https://www.instagram.com"],
    ["netflix", "https://www.netflix.com"],
    ["spotify", "https://www.spotify.com"],
    ["bbc", "https://www.bbc.com"],
    ["cnn", "https://www.cnn.com"],
    ["nytimes", "https://www.nytimes.com"],
    ["walmart", "https://www.walmart.com"],
    ["target", "https://www.target.com"],
    ["bestbuy", "https://www.bestbuy.com"],
    ["sonyliv", "https://www.sonyliv.com"],
    ["hulu", "https://www.hulu.com"],
    ["amazon prime video", "https://www.amazon.com/Amazon-Video"],
    ["disney+", "https://www.disneyplus.com"],
    ["apple music", "https://www.apple.com/music/"],
    ["twitch", "https://www.twitch.tv"],
    ["soundcloud", "https://soundcloud.com"],
    ["pandora", "https://www.pandora.com"],
    ["vimeo", "https://vimeo.com"],
    ["crunchyroll", "https://www.crunchyroll.com"],
    ["funimation", "https://www.funimation.com"],
    ["imdb", "https://www.imdb.com"],
    ["rotten tomatoes", "https://www.rottentomatoes.com"],
    ["metacritic", "https://www.metacritic.com"],
    ["ign", "https://www.ign.com"],
    ["gamespot", "https://www.gamespot.com"],
    ["polygon", "https://www.polygon.com"],
    ["kotaku", "https://kotaku.com"],
    ["google", "https://www.google.com"],
    ["facebook", "https://www.facebook.com"],
    ["yahoo", "https://www.yahoo.com"],
    ["the guardian", "https://www.theguardian.com"],
    ["forbes", "https://www.forbes.com"],
    ["the washington post", "https://www.washingtonpost.com"],
    ["national geographic", "https://www.nationalgeographic.com"],
    ["espn", "https://www.espn.com"],
    ["bbc news", "https://www.bbc.co.uk/news"],
    ["fox news", "https://www.foxnews.com"],
    ["cnn business", "https://www.cnn.com/business"],
    ["the huffington post", "https://www.huffpost.com"],
    ["buzzfeed", "https://www.buzzfeed.com"],
    ["techcrunch", "https://techcrunch.com"],
    ["mashable", "https://mashable.com"],
    ["the verge", "https://www.theverge.com"],
    ["wired", "https://www.wired.com"],
    ["ars technica", "https://arstechnica.com"],
    ["gizmodo", "https://gizmodo.com"],
    ["engadget", "https://www.engadget.com"],
    ["pc gamer", "https://www.pcgamer.com"],
    ["destructoid", "https://www.destructoid.com"],
    ["rolling stone", "https://www.rollingstone.com"],
    ["variety", "https://variety.com"],
    ["pitchfork", "https://pitchfork.com"],
    ["vanity fair", "https://www.vanityfair.com"],
    ["harvard business review", "https://hbr.org"],
    ["nature", "https://www.nature.com"],
    ["science", "https://www.sciencemag.org"],
    ["ted talks", "https://www.ted.com"],
    ["coursera", "https://www.coursera.org"],
    ["khan academy", "https://www.khanacademy.org"],
    ["google scholar", "https://scholar.google.com"],
    ["nasa", "https://www.nasa.gov"],
    ["the white house", "https://www.whitehouse.gov"],
    ["united nations", "https://www.un.org"],
    ["world health organization", "https://www.who.int"],
    ["quora", "https://www.quora.com"],
    ["medium", "https://medium.com"],
    ["flickr", "https://www.flickr.com"],
    ["pinterest", "https://www.pinterest.com"],
    ["tripadvisor", "https://www.tripadvisor.com"],
    ["yelp", "https://www.yelp.com"],
    ["coursera", "https://www.coursera.org"],
    ["udemy", "https://www.udemy.com"],
    ["edx", "https://www.edx.org"],
    ["skillshare", "https://www.skillshare.com"],
    ["tiktok", "https://www.tiktok.com"],
    ["snapchat", "https://www.snapchat.com"],
    ["telegram", "https://telegram.org"],
    ["discord", "https://discord.com"],
    ["whatsapp", "https://www.whatsapp.com"],
    ["signal", "https://signal.org"],
    ["zoom", "https://zoom.us"],
    ["microsoft teams", "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software"],
    ["openai", "https://www.openai.com"],
    ["tensorflow", "https://www.tensorflow.org"],
    ["pytorch", "https://pytorch.org"],
    ["kaggle", "https://www.kaggle.com"],
    ["towards data science", "https://towardsdatascience.com"],
    ["fast.ai", "https://www.fast.ai"],
    ["arxiv", "https://arxiv.org"],
    ["huggingface", "https://huggingface.co"],
    ["deepmind", "https://deepmind.com"],
    ["ai.google", "https://ai.google"],
    ["mlflow", "https://mlflow.org"],
    ["dataquest", "https://www.dataquest.io"],
    ["datacamp", "https://www.datacamp.com"],
    ["analytics vidhya", "https://www.analyticsvidhya.com"],
    ["machine learning mastery", "https://machinelearningmastery.com"],
    ["openml", "https://www.openml.org"],
    ["kdnuggets", "https://www.kdnuggets.com"],
    ["towards ai", "https://towardsai.net"],
    ["google AI", "https://ai.google/research"],
    ["ai trends", "https://aitrends.com"],
    ["youtube", "https://www.youtube.com"],
    ["wikipedia", "https://www.wikipedia.org"],
    ["github", "https://github.com"],
    ["stackoverflow", "https://stackoverflow.com"],
    ["amazon", "https://www.amazon.com"],
    ["reddit", "https://www.reddit.com"],
    ["twitter", "https://twitter.com"],
    ["linkedin", "https://www.linkedin.com"],
    ["ebay", "https://www.ebay.com"],
    ["instagram", "https://www.instagram.com"],
    ["netflix", "https://www.netflix.com"],
    ["spotify", "https://www.spotify.com"],
    ["bbc", "https://www.bbc.com"],
    ["cnn", "https://www.cnn.com"],
    ["nytimes", "https://www.nytimes.com"],
    ["walmart", "https://www.walmart.com"],
    ["target", "https://www.target.com"],
    ["bestbuy", "https://www.bestbuy.com"],
    ["sonyliv", "https://www.sonyliv.com"],
    ["hulu", "https://www.hulu.com"],
    ["amazon prime video", "https://www.amazon.com/Amazon-Video"],
    ["disney+", "https://www.disneyplus.com"],
    ["apple music", "https://www.apple.com/music/"],
    ["twitch", "https://www.twitch.tv"],
    ["soundcloud", "https://soundcloud.com"],
    ["pandora", "https://www.pandora.com"],
    ["vimeo", "https://vimeo.com"],
    ["crunchyroll", "https://www.crunchyroll.com"],
    ["funimation", "https://www.funimation.com"],
    ["imdb", "https://www.imdb.com"],
    ["rotten tomatoes", "https://www.rottentomatoes.com"],
    ["metacritic", "https://www.metacritic.com"],
    ["ign", "https://www.ign.com"],
    ["gamespot", "https://www.gamespot.com"],
    ["polygon", "https://www.polygon.com"],
    ["kotaku", "https://kotaku.com"],
    ["google", "https://www.google.com"],
    ["facebook", "https://www.facebook.com"],
    ["yahoo", "https://www.yahoo.com"],
    ["the guardian", "https://www.theguardian.com"],
    ["forbes", "https://www.forbes.com"],
    ["the washington post", "https://www.washingtonpost.com"],
    ["national geographic", "https://www.nationalgeographic.com"],
    ["espn", "https://www.espn.com"],
    ["bbc news", "https://www.bbc.co.uk/news"],
    ["fox news", "https://www.foxnews.com"],
    ["cnn business", "https://www.cnn.com/business"],
    ["the huffington post", "https://www.huffpost.com"],
    ["buzzfeed", "https://www.buzzfeed.com"],
    ["techcrunch", "https://techcrunch.com"],
    ["mashable", "https://mashable.com"],
    ["the verge", "https://www.theverge.com"],
    ["wired", "https://www.wired.com"],
    ["ars technica", "https://arstechnica.com"],
    ["gizmodo", "https://gizmodo.com"],
    ["engadget", "https://www.engadget.com"],
    ["pc gamer", "https://www.pcgamer.com"],
    ["destructoid", "https://www.destructoid.com"],
    ["rolling stone", "https://www.rollingstone.com"],
    ["variety", "https://variety.com"],
    ["pitchfork", "https://pitchfork.com"],
    ["vanity fair", "https://www.vanityfair.com"],
    ["harvard business review", "https://hbr.org"],
    ["nature", "https://www.nature.com"],
    ["science", "https://www.sciencemag.org"],
    ["ted talks", "https://www.ted.com"],
    ["coursera", "https://www.coursera.org"],
    ["khan academy", "https://www.khanacademy.org"],
    ["google scholar", "https://scholar.google.com"],
    ["nasa", "https://www.nasa.gov"],
    ["the white house", "https://www.whitehouse.gov"],
    ["united nations", "https://www.un.org"],
    ["world health organization", "https://www.who.int"],
    ["quora", "https://www.quora.com"],
    ["medium", "https://medium.com"],
    ["flickr", "https://www.flickr.com"],
    ["pinterest", "https://www.pinterest.com"],
    ["tripadvisor", "https://www.tripadvisor.com"],
    ["yelp", "https://www.yelp.com"],
    ["udemy", "https://www.udemy.com"],
    ["edx", "https://www.edx.org"],
    ["skillshare", "https://www.skillshare.com"],
    ["tiktok", "https://www.tiktok.com"],
    ["snapchat", "https://www.snapchat.com"],
    ["telegram", "https://telegram.org"],
    ["discord", "https://discord.com"],
    ["whatsapp", "https://www.whatsapp.com"],
    ["signal", "https://signal.org"],
    ["zoom", "https://zoom.us"],
    ["microsoft teams", "https://www.microsoft.com/en-us/microsoft-teams/group-chat-software"],
    ["openai", "https://www.openai.com"],
    ["tensorflow", "https://www.tensorflow.org"],
    ["pytorch", "https://pytorch.org"],
    ["kaggle", "https://www.kaggle.com"],
    ["towards data science", "https://towardsdatascience.com"],
    ["fast.ai", "https://www.fast.ai"],
    ["arxiv", "https://arxiv.org"],
    ["huggingface", "https://huggingface.co"],
    ["deepmind", "https://deepmind.com"],
    ["ai.google", "https://ai.google"],
    ["mlflow", "https://mlflow.org"],
    ["dataquest", "https://www.dataquest.io"],
    ["datacamp", "https://www.datacamp.com"],
    ["analytics vidhya", "https://www.analyticsvidhya.com"],
    ["machine learning mastery", "https://machinelearningmastery.com"],
    ["openml", "https://www.openml.org"],
    ["kdnuggets", "https://www.kdnuggets.com"],
    ["towards ai", "https://towardsai.net"],
    ["google ai", "https://ai.google/research"],
    ["ai trends", "https://aitrends.com"],
]

apps = [
            ["microsoft edge", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"],
            ["visual studio code", "C:\\Users\\rashi\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"],
            ["google chrome", "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"],
            ["pycharm", "C:\\Program Files\\JetBrains\\PyCharm Community Edition 2024.1\\bin\\pycharm64.exe"],
            ["jetbrains toolbox", "C:\\Users\\rashi\\AppData\\Local\\JetBrains\\Toolbox\\bin\\jetbrains-toolbox.exe"]
        ]
songs = [["song", "https://www.youtube.com/watch?v=MGwiCtsbB6k&list=RDMGwiCtsbB6k&start_radio=1"], ]

